# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20d58b71c78dac4735a297bebfe2d0ea883cdd9373c4ce9fe65bceca33e6ff076446045e2f4a9e568f6c9870ed5a151594281194abd1196a07806a4227dd9f67

test:
  secret_key_base: e161cdde5de8b2ab387a2d97d94c625451bab89cc5a33123986af9a107ede6049578f30837260957550640c2d0014505cc831ab1fa42991011b3c00d61b795a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
